version: '3.5'


services:
  registery-service:
    image: achrafchar/registery-service.0.0.1
    container_name: registery-service
    ports:
      - 8761:8761
    networks:
      - samnet

  config-service:
    image: achrafchar/config-service.0.0.1
    container_name: config-service
    ports:
      - 8888:8888
    environment:
      - EUREKA_CLIENT_SERVICE-URL_DEFAULTZONE=http://registery-service:8761/eureka
      - SPRING_ZIPKIN_BASEURL=http://zipkin-service:9411/
    networks:
      - samnet

  zipkin-service:
    image: openzipkin/zipkin:2.23
    container_name: zipkin-service
    ports:
      - 9411:9411
    restart: always #Restart if there is a problem starting up
    networks:
      - samnet

  axon-service:
    image: axoniq/axonserver
    container_name: axon-service
    ports:
      - 8024:8024
      - 8124:8124
    networks:
      - samnet

networks:
  samnet:
    name: sam-network1
    driver: bridge




