spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: https://github.com/celrati/schoolAbstractionManagerConfig
          clone-on-start: true
          strict-host-key-checking: false
          force-pull: true
server:
  port: 8888
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka