spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: https://github.com/celrati/schoolAbstractionManagerConfig
server:
  port: 8888
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka